### ISSUE TITLE
#6863 [DataCite] OAI-PMH server still not working

### ISSUE THREAD

**Issue by kjgarza** [datacite/oaip#36]
Not Found

request: https://search.test.datacite.org/public/api?q=laser&rows=50&start=0&sort=updated asc&fq=resourceTypeGeneral:dataset&fq=allocator_symbol:TIB&fq=updated:[0001-01-01T00:00:00Z TO 9999-12-31T23:59:59Z]&qt=/public/api&wt=javabin&version=2
	at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:430)
	at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:244)
	at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:89)
	... 33 more

**Comment by kjgarza** [comment]
very likely to be a problem with the path for the sorl container

**Comment by kjgarza** [comment]
Issues was fixed whenwe reversed SOLR container in : 1e1dff03a2675c97695a34b2f4fbd761e499fa0c

@mfenner can you review?

**Comment by mfenner** [comment]
This has been fixed.
